from config import settings


TOKEN = settings.UPTIME_BOT_TOKEN
ADMIN_ID = settings.UPTIME_ADMIN_ID
MAIN_BOT_USERNAME = settings.UPTIME_MAIN_BOT_USERNAME
LOG_FILE_PATH = settings.UPTIME_LOG_FILE_PATH
